"""Initial schema migration

Revision ID: 33a732bd5539
Revises: 
Create Date: 2026-05-29 01:11:07.696182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a732bd5539'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_anomaly_records_acknowledged'), 'anomaly_records', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_anomaly_records_severity'), 'anomaly_records', ['severity'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_prioritized_alerts_anomaly_id'), 'prioritized_alerts', ['anomaly_id'], unique=False)
    op.create_index(op.f('ix_prioritized_alerts_cooldown_until'), 'prioritized_alerts', ['cooldown_until'], unique=False)
    op.create_index(op.f('ix_prioritized_alerts_current_severity'), 'prioritized_alerts', ['current_severity'], unique=False)
    op.create_index(op.f('ix_prioritized_alerts_last_occurrence'), 'prioritized_alerts', ['last_occurrence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prioritized_alerts_last_occurrence'), table_name='prioritized_alerts')
    op.drop_index(op.f('ix_prioritized_alerts_current_severity'), table_name='prioritized_alerts')
    op.drop_index(op.f('ix_prioritized_alerts_cooldown_until'), table_name='prioritized_alerts')
    op.drop_index(op.f('ix_prioritized_alerts_anomaly_id'), table_name='prioritized_alerts')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_anomaly_records_severity'), table_name='anomaly_records')
    op.drop_index(op.f('ix_anomaly_records_acknowledged'), table_name='anomaly_records')
    # ### end Alembic commands ###
