from typing import List, Optional
from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field


class EnergyRecord(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    timestamp: datetime = Field(..., description="Timestamp of the energy grid reading")
    location: str = Field(..., description="Location or city name associated with the grid")
    grid_load_kw: Optional[float] = Field(None, description="Active power load on the grid in kW")
    solar_output_kw: Optional[float] = Field(None, description="Power generated by solar inputs in kW")
    energy_demand_kw: Optional[float] = Field(None, description="Total energy demand on the grid in kW")
    grid_stability_pct: Optional[float] = Field(None, description="Power grid stability percentage [0.0 - 100.0]")


class CurrentEnergyResponse(BaseModel):
    success: bool = Field(..., description="Indicator of a successful data fetch")
    fetched_at: datetime = Field(..., description="Timestamp when data was synced")
    records: List[EnergyRecord] = Field(default_factory=list, description="Latest grid energy readings")


class EnergyTrendsResponse(BaseModel):
    location: str = Field(..., description="Target location/city for trends")
    records: List[EnergyRecord] = Field(default_factory=list, description="Historical time-series series")
